### ISSUE TITLE
Evaluate head UI options

### ISSUE THREAD

**Issue by nickswalker** [homeskies/uw_common#2]
Now that we have a beautiful head touch screen, we're going to want to use it for some UI. [rws](https://github.com/hcrlab/rws) is a great candidate for serving up a web page that we could then display from the xavier. We should see what and how severe the breakage is in melodic.

**Comment by WxyElaine** [comment]
I just added both `node_modules` and `bower_components` to `.gitignore`. I tried to migrate `web_teleop` from `bower` to `yarn` yesterday, but the `polymer build` failed due to some dependency issues. So I discarded my changes and stick with `bower`.

**Comment by nickswalker** [comment]
Now that rws is functioning again and the first applications are running on the robot we are confident that this setup will work.
